# Generated by Django 6.0.6 on 2026-07-06 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_product_description_product_has_marking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Chegirma foizi')),
                ('scope', models.CharField(choices=[('ALL', 'Barcha mahsulotlar'), ('CATEGORY', "Kategoriya bo'yicha"), ('PRODUCT', 'Bitta mahsulot')], default='ALL', max_length=10, verbose_name='Qamrov')),
                ('start_date', models.DateField(verbose_name='Boshlanish')),
                ('end_date', models.DateField(verbose_name='Tugash')),
                ('is_active', models.BooleanField(default=True, verbose_name="Faol (qo'lda o'chirilmagan)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to='products.category')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to='products.product')),
            ],
            options={
                'verbose_name': 'Aksiya',
                'verbose_name_plural': 'Aksiyalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
