# Generated by Django 6.0.6 on 2026-07-05 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0003_store_activity_type_store_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kassa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Kassa nomi')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Balans')),
                ('is_active', models.BooleanField(default=True, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kassalar', to='stores.store', verbose_name="Do'kon")),
            ],
            options={
                'verbose_name': 'Kassa',
                'verbose_name_plural': 'Kassalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
