# Generated by Django 6.0.6 on 2026-07-05 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_product_description_product_has_marking_and_more'),
        ('stores', '0003_store_activity_type_store_balance'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Hujjat raqami')),
                ('comment', models.CharField(blank=True, max_length=500, null=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='stores.store', verbose_name="Do'kon")),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='suppliers.supplier', verbose_name='Yetkazib beruvchi')),
            ],
            options={
                'verbose_name': 'Накладная',
                'verbose_name_plural': 'Накладные',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Miqdor')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tannarx')),
                ('batch_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Partiya №')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Muddati')),
                ('line_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_receipt_items', to='products.product')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.stockreceipt')),
            ],
        ),
    ]
