# Generated by Django 6.0.6 on 2026-07-06 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0003_store_activity_type_store_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Kirim (naqd kirim)'), ('OUT', 'Chiqim (kassa xarajat)'), ('COLLECTION', 'Inkassatsiya (pul inkasso)')], max_length=12, verbose_name='Turi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Summa')),
                ('comment', models.CharField(blank=True, max_length=500, null=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_movements', to='stores.store')),
            ],
            options={
                'verbose_name': 'Kassa harakati',
                'verbose_name_plural': 'Kassa harakatlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
