# Generated by Django 6.0.6 on 2026-07-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='can_create_products',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_create_stores',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_create_suppliers',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_delete_products',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_delete_sales',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_delete_stores',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_edit_products',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_edit_stores',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_view_products',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_view_sales',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_view_shifts',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_view_stores',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_view_suppliers',
        ),
        migrations.AddField(
            model_name='role',
            name='is_system',
            field=models.BooleanField(default=False, verbose_name='Tizim roli'),
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.JSONField(blank=True, default=dict, verbose_name='Ruxsatlar'),
        ),
    ]
