# Generated by Django 6.0.6 on 2026-07-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ismi')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Manzil')),
                ('comment', models.CharField(blank=True, max_length=500, null=True, verbose_name='Izoh')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Chegirma (%)')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Ball')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mijoz',
                'verbose_name_plural': 'Mijozlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
