# Generated by Django 6.0.6 on 2026-07-06 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_product_description_product_has_marking_and_more'),
        ('stores', '0003_store_activity_type_store_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Raqam')),
                ('comment', models.CharField(blank=True, max_length=500, null=True, verbose_name='Izoh')),
                ('status', models.CharField(choices=[('COMPLETED', 'Bajarildi'), ('CANCELLED', 'Bekor qilindi')], default='COMPLETED', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('destination_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='stores.store', verbose_name='Maqsad filial')),
                ('source_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='stores.store', verbose_name='Manba filial')),
            ],
            options={
                'verbose_name': 'Transfer',
                'verbose_name_plural': 'Transferlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Miqdor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_items', to='products.product')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transfers.stocktransfer')),
            ],
        ),
    ]
