# Generated by Django 6.0.6 on 2026-07-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Do'kon nomi")),
                ('address', models.TextField(blank=True, null=True, verbose_name='Manzili')),
            ],
        ),
    ]
