# Generated by Django 6.0.6 on 2026-07-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Kompaniya nomi')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Soliq (%)')),
                ('currency', models.CharField(default="SO'M", max_length=10, verbose_name='Valyuta')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Manzil')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tizim sozlamasi',
                'verbose_name_plural': 'Tizim sozlamalari',
            },
        ),
        migrations.AddField(
            model_name='store',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Holati'),
        ),
        migrations.AddField(
            model_name='store',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon raqami'),
        ),
        migrations.AddField(
            model_name='store',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=255, verbose_name="Do'kon/Filial nomi"),
        ),
    ]
