# Generated by Django 6.0.6 on 2026-07-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_systemsettings_store_created_at_store_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='activity_type',
            field=models.CharField(choices=[('dokon', "🏪 Do'kon"), ('restoran', '🍽️ Restoran')], default='dokon', max_length=20, verbose_name='Faoliyat turi'),
        ),
        migrations.AddField(
            model_name='store',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Balans'),
        ),
    ]
