# Generated by Django 6.0.6 on 2026-07-02 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('stores', '0002_systemsettings_store_created_at_store_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Umumiy summa')),
                ('paid_cash', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name="Naqd to'lov")),
                ('paid_card', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name="Karta orqali to'lov")),
                ('payment_method', models.CharField(choices=[('CASH', 'Naqd'), ('CARD', 'Plastik Karta'), ('MIXED', 'Aralash (Naqd + Karta)')], default='CASH', max_length=10, verbose_name="To'lov turi")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sotilgan vaqti')),
                ('cashier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL, verbose_name='Kassir')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='stores.store', verbose_name="Do'kon")),
            ],
            options={
                'verbose_name': 'Savdo',
                'verbose_name_plural': 'Savdolar',
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Miqdori (Dona/Kg)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Sotilgan narxi')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Jami narxi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='products.product', verbose_name='Mahsulot')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale', verbose_name='Chek')),
            ],
        ),
    ]
