# Generated by Django 6.0.6 on 2026-07-02 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        ('stores', '0002_systemsettings_store_created_at_store_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='Smena ochilgan vaqti')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Smena yopilgan vaqti')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Ochilishdagi pul (Kassa)')),
                ('closing_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Yopilishdagi pul')),
                ('is_open', models.BooleanField(default=True, verbose_name='Smena holati')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='stores.store')),
            ],
            options={
                'verbose_name': 'Smena',
                'verbose_name_plural': 'Smenalar',
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='sales.shift'),
        ),
    ]
