# Generated by Django 6.0.6 on 2026-07-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_shift_sale_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Naqd'), ('CARD', 'Plastik Karta'), ('MIXED', 'Aralash (Naqd + Karta)'), ('CREDIT', 'Nasiya')], default='CASH', max_length=10, verbose_name="To'lov turi"),
        ),
    ]
