# Generated by Django 6.0.6 on 2026-07-02 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0002_systemsettings_store_created_at_store_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Kategoriya nomi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Mahsulot nomi')),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Shtrix-kod')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Tannarxi')),
                ('selling_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Sotish narxi')),
                ('stock', models.DecimalField(decimal_places=3, default=0.0, max_digits=10, verbose_name='Ombordagi qoldiq')),
                ('is_weighted', models.BooleanField(default=False, verbose_name='Vaznli mahsulot (Kg/Litr)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='Kategoriyasi')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='stores.store', verbose_name="Do'kon")),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'unique_together': {('store', 'barcode')},
            },
        ),
    ]
