# Generated by Django 6.0.6 on 2026-07-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_marking',
            field=models.BooleanField(default=False, verbose_name='Markirovka'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_vat',
            field=models.BooleanField(default=True, verbose_name='НДС'),
        ),
        migrations.AddField(
            model_name='product',
            name='plu',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PLU kod'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Yetkazib beruvchi'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('dona', 'Dona'), ('kg', 'Kilogramm'), ('litr', 'Litr'), ('metr', 'Metr'), ('quti', 'Quti')], default='dona', max_length=10, verbose_name='Birlik'),
        ),
    ]
